# Generated by Django 3.2.5 on 2021-08-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_in_context', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srabook',
            name='orig_book',
        ),
        migrations.AlterField(
            model_name='srabook',
            name='title',
            field=models.CharField(help_text='Getting the Main Idea', max_length=200),
        ),
    ]
