# Generated by Django 3.2.5 on 2021-08-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_in_context', '0002_auto_20210825_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='srabook',
            name='WTF',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
