# Generated by Django 3.2.5 on 2021-08-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_in_context', '0003_srabook_wtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='srabook',
            name='orig_book',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
