# Generated by Django 3.2.5 on 2021-08-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_in_context', '0004_srabook_orig_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srabook',
            name='WTF',
        ),
        migrations.RemoveField(
            model_name='srabook',
            name='orig_book',
        ),
    ]
