# Generated by Django 3.2.4 on 2021-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SightWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('orig_set', models.IntegerField(max_length=2)),
                ('orig_num', models.IntegerField(max_length=2)),
            ],
        ),
    ]
