# Generated by Django 3.2.4 on 2021-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightword',
            name='orig_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sightword',
            name='orig_set',
            field=models.IntegerField(),
        ),
    ]
