# Generated by Django 3.2.5 on 2021-08-23 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='SightWordSentences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentences', models.TextField(blank=True, help_text='Sentences - Max 1000 characters', max_length=1000)),
                ('sight_word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightwords.sightword')),
            ],
        ),
    ]
