# Generated by Django 4.0.4 on 2022-06-21 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvstoryquestion',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vv_stories.vvstory'),
            preserve_default=False,
        ),
    ]
