# Generated by Django 4.0.4 on 2022-06-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0002_vvstoryquestion_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vvstoryquestion',
            name='story',
        ),
        migrations.DeleteModel(
            name='VVStory',
        ),
        migrations.DeleteModel(
            name='VVStoryQuestion',
        ),
    ]
