# Generated by Django 3.2.5 on 2022-06-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0004_vvstory_vvstoryquestion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vvstory',
            unique_together={('book', 'number')},
        ),
    ]
