# Generated by Django 3.2.5 on 2022-06-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0005_alter_vvstory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vvstory',
            name='story_type',
            field=models.CharField(choices=[('SentBySent', 'Sentence by Sentence'), ('MultiSent', 'Multiple Sentence'), ('WholePara', 'Whole Paragraph'), ('Para', 'Paragraph by Paragraph'), ('CustomType', 'Custom')], default='SentBySent', max_length=10),
        ),
    ]
