# Generated by Django 3.2.4 on 2021-07-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='note',
            field=models.TextField(max_length=1000),
        ),
    ]
