# Generated by Django 3.2.4 on 2021-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0002_alter_lessonplan_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='sight_words_end',
            field=models.PositiveSmallIntegerField(default=25, help_text='enter 1-1000, greater than sight words end'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='sight_words_start',
            field=models.PositiveSmallIntegerField(default=1, help_text='enter 1-1000, less than sight words end'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='syllable_words_end',
            field=models.PositiveSmallIntegerField(default=25, help_text='enter 1-2500, greater than syllable words end'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='syllable_words_start',
            field=models.PositiveSmallIntegerField(default=1, help_text='enter 1-2500, less than syllable words end'),
        ),
    ]
