# Generated by Django 3.2.4 on 2021-07-08 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('students', '0002_auto_20210707_2332'),
        ('lessonplans', '0003_auto_20210708_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSightWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sight_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightwords.sightword')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
