# Generated by Django 3.2.4 on 2021-07-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0004_personalsightwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='syllable_list',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
