# Generated by Django 3.2.4 on 2021-07-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0005_lessonplan_syllable_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='syllable_list',
        ),
    ]
