# Generated by Django 3.2.4 on 2021-07-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0006_remove_lessonplan_syllable_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='air_write_words',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
