# Generated by Django 3.2.4 on 2021-07-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0008_auto_20210716_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='sight_word_list',
            field=models.CharField(default='1-5, 8, 11-13', help_text='e.g. 1-5, 8, 11-13', max_length=50),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='syllable_word_list',
            field=models.CharField(default='10-15, 18, 111-113', help_text='e.g. 9, 12-20, 110-113', max_length=50),
        ),
    ]
