# Generated by Django 3.2.4 on 2021-07-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0009_auto_20210716_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonplan',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='lessonplan',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
