# Generated by Django 3.2.4 on 2021-07-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210716_2153'),
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0010_auto_20210716_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalSightWords',
            new_name='PersonalSightWord',
        ),
    ]
