# Generated by Django 3.2.4 on 2021-07-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0011_rename_personalsightwords_personalsightword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalsightword',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='personalsightword',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='air_write_words',
            field=models.TextField(blank=True, help_text='max 200 characters', max_length=200),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='note',
            field=models.TextField(blank=True, help_text='max 1000 characters', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='sight_words_end',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='sight_words_start',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='syllable_words_end',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='syllable_words_start',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
