# Generated by Django 3.2.4 on 2021-07-19 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0013_testmaster_testslave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testslave',
            name='mstr_name',
        ),
        migrations.DeleteModel(
            name='TestMaster',
        ),
        migrations.DeleteModel(
            name='TestSlave',
        ),
    ]
