# Generated by Django 3.2.4 on 2021-07-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0014_auto_20210718_2255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalSightWord',
        ),
    ]
