# Generated by Django 3.2.4 on 2021-07-19 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('students', '0004_auto_20210716_2153'),
        ('lessonplans', '0015_delete_personalsightword'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalSightWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sight_word', models.ManyToManyField(to='sightwords.SightWord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
