# Generated by Django 3.2.4 on 2021-07-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0003_alter_syllableword_name'),
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0016_personalsightword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='sight_word_list',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='sight_word_list',
            field=models.ManyToManyField(to='sightwords.SightWord'),
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='syllable_word_list',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='syllable_word_list',
            field=models.ManyToManyField(to='syllablewords.SyllableWord'),
        ),
    ]
