# Generated by Django 3.2.4 on 2021-07-21 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0017_auto_20210718_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsightword',
            name='sight_word',
        ),
        migrations.AddField(
            model_name='personalsightword',
            name='sight_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sightwords.sightword'),
            preserve_default=False,
        ),
    ]
