# Generated by Django 3.2.4 on 2021-07-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0018_auto_20210721_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSightWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
                ('sight_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightwords.sightword')),
            ],
        ),
    ]
