# Generated by Django 3.2.5 on 2021-07-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0019_lessonsightwordlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='sight_word_list',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='syllable_word_list',
        ),
    ]
