# Generated by Django 3.2.5 on 2021-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0020_auto_20210725_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='sight_word_list',
            field=models.ManyToManyField(through='lessonplans.LessonSightWordList', to='sightwords.SightWord'),
        ),
    ]
