# Generated by Django 3.2.5 on 2021-07-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0021_lessonplan_sight_word_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonsightwordlist',
            unique_together={('sight_word', 'lesson_plan')},
        ),
    ]
