# Generated by Django 3.2.5 on 2021-07-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0022_alter_lessonsightwordlist_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessonsightwordlist',
            unique_together=set(),
        ),
    ]
