# Generated by Django 3.2.5 on 2021-07-26 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0003_alter_syllableword_name'),
        ('lessonplans', '0024_alter_lessonsightwordlist_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSyllableWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
                ('syllable_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllablewords.syllableword')),
            ],
            options={
                'unique_together': {('syllable_word', 'lesson_plan')},
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='syllable_word_list',
            field=models.ManyToManyField(through='lessonplans.LessonSyllableWordList', to='syllablewords.SyllableWord'),
        ),
    ]
