# Generated by Django 3.2.5 on 2021-07-27 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0025_auto_20210726_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='scheduled',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
