# Generated by Django 3.2.5 on 2021-07-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0028_alter_lessonplan_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsightword',
            name='last_grade',
            field=models.IntegerField(choices=[(0, 'Null'), (1, 'Snail'), (2, 'Bike'), (3, 'Jet'), (4, 'Graduate')], default=0),
            preserve_default=False,
        ),
    ]
