# Generated by Django 3.2.5 on 2021-07-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0029_personalsightword_last_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsightword',
            name='snail_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
