# Generated by Django 3.2.5 on 2021-07-28 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0030_personalsightword_snail_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsightword',
            name='snail_num',
            field=models.IntegerField(default=0),
        ),
    ]
