# Generated by Django 3.2.5 on 2021-07-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0031_alter_personalsightword_snail_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsightword',
            name='last_grade',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Snail'), (2, 'Bike'), (3, 'Jet'), (4, 'Graduate')], default=0),
        ),
    ]
