# Generated by Django 3.2.5 on 2021-07-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0032_alter_personalsightword_last_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsightword',
            name='bike_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalsightword',
            name='graduate_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalsightword',
            name='jet_num',
            field=models.IntegerField(default=0),
        ),
    ]
