# Generated by Django 3.2.5 on 2021-07-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0033_auto_20210727_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalsightword',
            name='bike_num',
            field=models.IntegerField(default=0, help_text='# of times bike was scored'),
        ),
        migrations.AlterField(
            model_name='personalsightword',
            name='graduate_num',
            field=models.IntegerField(default=0, help_text='# of times graduate was scored'),
        ),
        migrations.AlterField(
            model_name='personalsightword',
            name='jet_num',
            field=models.IntegerField(default=0, help_text='# of times jet was scored'),
        ),
        migrations.AlterField(
            model_name='personalsightword',
            name='snail_num',
            field=models.IntegerField(default=0, help_text='# of times snail was scored'),
        ),
    ]
