# Generated by Django 3.2.5 on 2021-07-28 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessonplans', '0034_auto_20210727_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='scheduled',
            field=models.DateTimeField(help_text='scheduled time for lesson to be given'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='assigned tutor to give lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
