# Generated by Django 3.2.5 on 2021-07-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0035_auto_20210727_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='note',
            field=models.TextField(blank=True, help_text='Notes for the tutor - Max 1000 characters', max_length=1000),
        ),
    ]
