# Generated by Django 3.2.5 on 2021-08-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0006_affix'),
        ('lessonplans', '0037_alter_lessonplan_scheduled'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMultiSyllableWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
                ('multisyllable_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllablewords.multisyllableword')),
            ],
            options={
                'unique_together': {('multisyllable_word', 'lesson_plan')},
            },
        ),
        migrations.CreateModel(
            name='LessonAffixWordList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('affix_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syllablewords.affix')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
            ],
            options={
                'unique_together': {('affix_word', 'lesson_plan')},
            },
        ),
    ]
