# Generated by Django 3.2.5 on 2021-08-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0006_affix'),
        ('lessonplans', '0038_lessonaffixwordlist_lessonmultisyllablewordlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='affix_word_list',
            field=models.ManyToManyField(through='lessonplans.LessonAffixWordList', to='syllablewords.Affix'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='multisyllable_word_list',
            field=models.ManyToManyField(through='lessonplans.LessonMultiSyllableWordList', to='syllablewords.MultiSyllableWord'),
        ),
    ]
