# Generated by Django 3.2.5 on 2021-08-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0016_alter_hackablewordset_title'),
        ('lessonplans', '0039_auto_20210809_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonHackableWordSetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hackable_word_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackablesheets.hackablewordset')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
            ],
            options={
                'unique_together': {('hackable_word_set', 'lesson_plan')},
            },
        ),
        migrations.CreateModel(
            name='LessonHackableSentenceSetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hackable_sentence_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackablesheets.hackablesentenceset')),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
            ],
            options={
                'unique_together': {('hackable_sentence_set', 'lesson_plan')},
            },
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='hackable_sentence_set_list',
            field=models.ManyToManyField(through='lessonplans.LessonHackableSentenceSetList', to='hackablesheets.HackableSentenceSet'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='hackable_word_set_list',
            field=models.ManyToManyField(through='lessonplans.LessonHackableWordSetList', to='hackablesheets.HackableWordSet'),
        ),
    ]
