# Generated by Django 3.2.5 on 2021-08-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('lessonplans', '0040_auto_20210809_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='sight_word_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonSightWordList', to='sightwords.SightWord'),
        ),
    ]
