# Generated by Django 3.2.5 on 2021-08-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0016_alter_hackablewordset_title'),
        ('syllablewords', '0006_affix'),
        ('lessonplans', '0041_alter_lessonplan_sight_word_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonplan',
            name='affix_word_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonAffixWordList', to='syllablewords.Affix'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='hackable_sentence_set_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonHackableSentenceSetList', to='hackablesheets.HackableSentenceSet'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='hackable_word_set_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonHackableWordSetList', to='hackablesheets.HackableWordSet'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='multisyllable_word_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonMultiSyllableWordList', to='syllablewords.MultiSyllableWord'),
        ),
        migrations.AlterField(
            model_name='lessonplan',
            name='syllable_word_list',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonSyllableWordList', to='syllablewords.SyllableWord'),
        ),
    ]
