# Generated by Django 3.2.5 on 2021-08-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonplans', '0042_auto_20210811_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='sight_words_end',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='sight_words_start',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='syllable_words_end',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='syllable_words_start',
        ),
    ]
