# Generated by Django 4.0.4 on 2022-06-24 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0004_vvstory_vvstoryquestion'),
        ('lessonplans', '0043_auto_20210815_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVVStoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='vv_story',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonVVStoryList', to='vv_stories.vvstory'),
        ),
        migrations.AddField(
            model_name='lessonvvstorylist',
            name='lesson_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan'),
        ),
        migrations.AddField(
            model_name='lessonvvstorylist',
            name='vv_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vv_stories.vvstory'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonvvstorylist',
            unique_together={('vv_story', 'lesson_plan')},
        ),
    ]
