# Generated by Django 3.2.5 on 2022-06-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0005_alter_vvstory_unique_together'),
        ('lessonplans', '0043_auto_20210815_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonVVStoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lesson_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessonplans.lessonplan')),
                ('vv_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vv_stories.vvstory')),
            ],
            options={
                'unique_together': {('vv_story', 'lesson_plan')},
            },
        ),
    ]
