# Generated by Django 3.2.5 on 2022-06-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vv_stories', '0005_alter_vvstory_unique_together'),
        ('lessonplans', '0044_lessonvvstorylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='vv_story',
            field=models.ManyToManyField(blank=True, through='lessonplans.LessonVVStoryList', to='vv_stories.VVStory'),
        ),
    ]
