# Generated by Django 3.2.5 on 2021-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackableSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('orig_book', models.IntegerField()),
                ('orig_num', models.IntegerField()),
            ],
        ),
    ]
