# Generated by Django 3.2.5 on 2021-07-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackablesheet',
            name='name',
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='note_bottom',
            field=models.CharField(blank=True, help_text='i.e. Remember: Try to start a syllable...', max_length=500),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='note_top',
            field=models.CharField(blank=True, help_text='i.e. Finger Break and Read', max_length=100),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='subtitle',
            field=models.CharField(blank=True, help_text='i.e. some easy initial blends', max_length=60),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='title',
            field=models.CharField(default='Title', help_text='i.e. CCV', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word10',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word11',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word12',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word13',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word14',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word15',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word16',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word17',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word18',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word19',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word20',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word5',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word6',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word7',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word8',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='hackablesheet',
            name='word9',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
