# Generated by Django 3.2.5 on 2021-07-31 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0002_auto_20210731_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HackableSheet',
            new_name='HackableWordSet',
        ),
    ]
