# Generated by Django 3.2.5 on 2021-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0003_rename_hackablesheet_hackablewordset'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackableSentenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='i.e. CCV', max_length=60)),
                ('subtitle', models.CharField(blank=True, help_text='i.e. some easy initial blends', max_length=60)),
                ('note_top', models.CharField(blank=True, help_text='i.e. Finger Break and Read', max_length=100)),
                ('note_bottom', models.CharField(blank=True, help_text='i.e. Remember: Try to start a syllable...', max_length=500)),
                ('order', models.IntegerField(unique=True)),
                ('orig_book', models.IntegerField()),
                ('orig_num', models.IntegerField()),
                ('word1', models.CharField(blank=True, max_length=25)),
                ('word2', models.CharField(blank=True, max_length=25)),
                ('word3', models.CharField(blank=True, max_length=25)),
                ('word4', models.CharField(blank=True, max_length=25)),
                ('word5', models.CharField(blank=True, max_length=25)),
                ('word6', models.CharField(blank=True, max_length=25)),
                ('word7', models.CharField(blank=True, max_length=25)),
                ('word8', models.CharField(blank=True, max_length=25)),
                ('word9', models.CharField(blank=True, max_length=25)),
                ('word10', models.CharField(blank=True, max_length=25)),
                ('sentence1', models.CharField(blank=True, max_length=100)),
                ('sentence2', models.CharField(blank=True, max_length=100)),
                ('sentence3', models.CharField(blank=True, max_length=100)),
                ('sentence4', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
