# Generated by Django 3.2.5 on 2021-08-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sightwords', '0002_auto_20210626_1611'),
        ('hackablesheets', '0004_hackablesentenceset'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackablewordset',
            name='orig_book_title',
            field=models.CharField(default='Title', help_text='i.e. VC & CCV', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestDelete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='i.e. CCV', max_length=60)),
                ('subtitle', models.CharField(blank=True, help_text='i.e. some easy initial blends', max_length=60)),
                ('note_top', models.CharField(blank=True, help_text='i.e. Finger Break and Read', max_length=100)),
                ('note_bottom', models.CharField(blank=True, help_text='i.e. Remember: Try to start a syllable...', max_length=500)),
                ('order', models.IntegerField(unique=True)),
                ('orig_book', models.IntegerField()),
                ('orig_num', models.IntegerField()),
                ('word1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightwords.sightword')),
            ],
        ),
    ]
