# Generated by Django 3.2.5 on 2021-08-01 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0005_auto_20210731_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDelete',
        ),
    ]
