# Generated by Django 3.2.5 on 2021-08-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0006_delete_testdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackablewordset',
            name='order',
            field=models.IntegerField(help_text='unique consecutive #', unique=True),
        ),
    ]
