# Generated by Django 3.2.5 on 2021-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0007_alter_hackablewordset_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackableBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_book_title', models.CharField(help_text='i.e. VC & CCV', max_length=100)),
                ('orig_book', models.IntegerField()),
                ('orig_num', models.IntegerField()),
            ],
        ),
    ]
