# Generated by Django 3.2.5 on 2021-08-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0008_hackablebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackablebook',
            old_name='orig_book_title',
            new_name='title',
        ),
    ]
