# Generated by Django 3.2.5 on 2021-08-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0009_rename_orig_book_title_hackablebook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackablebook',
            name='orig_book',
            field=models.IntegerField(help_text='original book # 1-6'),
        ),
        migrations.AlterField(
            model_name='hackablebook',
            name='orig_num',
            field=models.IntegerField(help_text='original # in book # 1-34'),
        ),
    ]
