# Generated by Django 3.2.5 on 2021-08-01 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0010_auto_20210731_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackablebook',
            name='orig_num',
        ),
    ]
