# Generated by Django 3.2.5 on 2021-08-01 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0011_remove_hackablebook_orig_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackablewordset',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hackablesheets.hackablebook'),
            preserve_default=False,
        ),
    ]
