# Generated by Django 3.2.5 on 2021-08-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0013_hackablesentenceset_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackablesentenceset',
            name='orig_book',
        ),
        migrations.RemoveField(
            model_name='hackablewordset',
            name='orig_book',
        ),
        migrations.RemoveField(
            model_name='hackablewordset',
            name='orig_book_title',
        ),
        migrations.AlterField(
            model_name='hackablesentenceset',
            name='title',
            field=models.CharField(help_text='Sheet Title - i.e. CCV', max_length=60),
        ),
        migrations.AlterField(
            model_name='hackablewordset',
            name='orig_num',
            field=models.IntegerField(help_text='original sheet #'),
        ),
        migrations.AlterField(
            model_name='hackablewordset',
            name='title',
            field=models.CharField(help_text='Sheet Title - i.e. CCV', max_length=60),
        ),
    ]
