# Generated by Django 3.2.5 on 2021-08-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0014_auto_20210731_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackablesentenceset',
            name='title',
            field=models.CharField(blank=True, help_text='Sheet Title - i.e. CCV', max_length=60),
        ),
    ]
