# Generated by Django 3.2.5 on 2021-08-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0015_alter_hackablesentenceset_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackablewordset',
            name='title',
            field=models.CharField(blank=True, help_text='Sheet Title - i.e. CCV', max_length=60),
        ),
    ]
