# Generated by Django 3.2.5 on 2021-08-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0016_alter_hackablewordset_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackablesentenceset',
            name='order',
        ),
        migrations.RemoveField(
            model_name='hackablewordset',
            name='order',
        ),
    ]
