# Generated by Django 3.2.5 on 2021-08-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0017_auto_20210822_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackablesentenceset',
            name='note_bottom',
        ),
        migrations.RemoveField(
            model_name='hackablesentenceset',
            name='note_top',
        ),
        migrations.RemoveField(
            model_name='hackablewordset',
            name='note_bottom',
        ),
        migrations.RemoveField(
            model_name='hackablewordset',
            name='note_top',
        ),
        migrations.AlterField(
            model_name='hackablesentenceset',
            name='orig_num',
            field=models.IntegerField(help_text='sheet #'),
        ),
    ]
