# Generated by Django 3.2.5 on 2021-08-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0018_auto_20210822_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackablebook',
            name='orig_book',
            field=models.IntegerField(help_text='book #'),
        ),
        migrations.AlterField(
            model_name='hackablewordset',
            name='orig_num',
            field=models.IntegerField(help_text='sheet #'),
        ),
    ]
