# Generated by Django 3.2.5 on 2021-08-24 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0019_auto_20210822_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackablesentenceset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackablesentenceset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hackablewordset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackablewordset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
