# Generated by Django 3.2.5 on 2021-08-26 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hackablesheets', '0020_auto_20210824_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackablebook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackablebook',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
