# Generated by Django 3.2.4 on 2021-06-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllableWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('order', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=15, unique=True)),
                ('orig_box', models.IntegerField()),
                ('orig_set', models.IntegerField()),
                ('orig_num', models.IntegerField()),
            ],
        ),
    ]
