# Generated by Django 3.2.4 on 2021-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0002_alter_syllableword_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllableword',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
