# Generated by Django 3.2.5 on 2021-07-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0003_alter_syllableword_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllableword',
            old_name='orig_set',
            new_name='orig_book',
        ),
    ]
