# Generated by Django 3.2.5 on 2021-08-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0004_rename_orig_set_syllableword_orig_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiSyllableWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('order', models.IntegerField(unique=True)),
                ('type', models.CharField(max_length=15)),
            ],
        ),
    ]
