# Generated by Django 3.2.5 on 2021-08-23 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syllablewords', '0006_affix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multisyllableword',
            name='order',
        ),
        migrations.RemoveField(
            model_name='syllableword',
            name='order',
        ),
    ]
